version: '3.7'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 5000:5000
    environment:
      - "articles"
    depends_on:
      - elasticsearch
      - bertserving

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200

  bertserving:
    container_name: bert
    build: ./bertserving
    ports:
      - 5555:5555
      - 5556:5556
    environment:
      - PATH_MODEL=${PATH_MODEL}
    volumes:
      - ${PATH_MODEL}:/model

volumes:
  es-data:
    driver: local
